# Generated by Django 5.2.4 on 2025-08-18 08:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 8, 18)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
